name: Solo Dev Auto-Approve & Merge

on:
  pull_request:
    types: [labeled, opened, reopened, synchronize]

jobs:
  auto-approve-and-merge:
    if: |
      github.event.pull_request.user.login == 'ReaveND' &&
      contains(github.event.pull_request.labels.*.name, 'auto-merge')
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
